sudo: required
dist: trusty
os: linux
language: node_js
node_js:
- '8'
python:
- '3.4'
cache:
  directories:
  - node_modules
before_install:
- echo $authfile | gpg --passphrase-fd 0 src/auth.json.gpg
- sudo apt-get update -y
- sudo apt-get install -y libcairo2-dev libjpeg-dev libpango1.0-dev libgif-dev build-essential
  g++ python3.4
- npm install -g node-pre-gyp node-gyp yarn
- echo "alias python=python3" >> .bashrc
- source .bashrc
before_script:
- yarn add sqlite
install:
- yarn install
script:
- yarn run lint
- yarn test
notifications:
  email: false
env:
  global:
    secure: xMR55FUusjf3mZ/pWUERQRdBlhY/vjW6vnOaINdCPF8dFymgTCm4jueZ3FIO0+AnL3ST0yttFGzrDj1VjlLeknIn644cu8bT48tEibWX5SASwpPYzJkfyxtvyyyqsH6qVNvuAdO/IOBUT+b47uj+myJJPB/gC2gqhzFSDAWDr4LJ+M0IIWxlMu9JHbWBucPWyXpWVu33ktBtuL9EuEhNbLKFsx4z1OZUCHOMpZ1q8+CTbGJMoeMNGnLOSdyXHV6l0IlASUlSq1nCuduy85305aWBUsD4qH5prIYw4Z4azEYf6vMiosGMM43eJ8Ks4VTRLmyQFr6RGHY3apq092w/7VlPH3NEvO2dhG+M8b89yYH5BfoVvi2ui/VZI51g/1Or/wQOA8ksdvVeemzOB8rRpTMviemHAKNoY7cyXw+Kz7DvSIs7Zq0GoaDWLkMdDnh+e/evQyUorn8PfMPG0xRg7eo+lRx7z7RoqDV5jhwwEBcu3BQ4NAYKJzIWn/7N+BCSq7XXaKBmr/F5ADL5ZlJUqPiyXFFZRp5GqD4ME8APG1tYIwfyH/G2BKRWLVmjeQXGCKByEYJ9ZqxREZNwbZVI64vthWtVa5nqgkHh57bmWvuflOyBx8MyxunIa/RkE8afTU83adTpFkk9syIOp1Vba+0zlkiOTzmDF/2/pDCGFEk=

env:
  global:
    secure: xMR55FUusjf3mZ/pWUERQRdBlhY/vjW6vnOaINdCPF8dFymgTCm4jueZ3FIO0+AnL3ST0yttFGzrDj1VjlLeknIn644cu8bT48tEibWX5SASwpPYzJkfyxtvyyyqsH6qVNvuAdO/IOBUT+b47uj+myJJPB/gC2gqhzFSDAWDr4LJ+M0IIWxlMu9JHbWBucPWyXpWVu33ktBtuL9EuEhNbLKFsx4z1OZUCHOMpZ1q8+CTbGJMoeMNGnLOSdyXHV6l0IlASUlSq1nCuduy85305aWBUsD4qH5prIYw4Z4azEYf6vMiosGMM43eJ8Ks4VTRLmyQFr6RGHY3apq092w/7VlPH3NEvO2dhG+M8b89yYH5BfoVvi2ui/VZI51g/1Or/wQOA8ksdvVeemzOB8rRpTMviemHAKNoY7cyXw+Kz7DvSIs7Zq0GoaDWLkMdDnh+e/evQyUorn8PfMPG0xRg7eo+lRx7z7RoqDV5jhwwEBcu3BQ4NAYKJzIWn/7N+BCSq7XXaKBmr/F5ADL5ZlJUqPiyXFFZRp5GqD4ME8APG1tYIwfyH/G2BKRWLVmjeQXGCKByEYJ9ZqxREZNwbZVI64vthWtVa5nqgkHh57bmWvuflOyBx8MyxunIa/RkE8afTU83adTpFkk9syIOp1Vba+0zlkiOTzmDF/2/pDCGFEk=
