sudo: required
dist: trusty
os: linux
language: node_js
node_js:
- '8'
cache:
  directories:
  - node_modules
before_install:
- if [ ${TRAVIS_PULL_REQUEST} == false]; then openssl aes-256-cbc -d -k "$authdecrypt" -in src/auth.json.enc -out src/auth.json; fi
- sudo apt-get update -y
- sudo apt-get install -y libcairo2-dev libjpeg-dev libpango1.0-dev libgif-dev build-essential
  g++ python3.4
- npm install -g node-pre-gyp node-gyp yarn
- echo "alias python=python3" >> .bashrc
- source .bashrc
before_script:
- yarn add sqlite
install:
- yarn install
script:
- yarn run lintfix
- yarn run lint
- if [ ${TRAVIS_PULL_REQUEST} == false]]; then yarn test; fi
notifications:
  email: false
env:
  global:
    secure: ZlRdiSXK290tWYFD0ZMha9bR2rrMwy+5ZvtjtFTpY3mhNKAWDMSal9NzobngcbFv+24lEVpkXGmYiwpOA+rJGYnGmeCStCsGABka0421NcV4F2OoFICUYgnedVmY06Xg2iqhS1PNxQR4xL8LMVX74DA/iuCYboU7s8lMU3/SfM7lsz0WD+UdNcuKJe/Qmi+CnGmrYgdKiy/CoBhHrW1gRZlMYxW3hSjZJn7Yq/AJIQTRfPsqHix+zgGjfjMTEwZFSe5YPVR/wCZRz6YTtkWNTMNY3ClKV8qLvUyo00mkpJNDMEslY6b0HoCi5OEE3/lwzTEH6vi+jBQ2hnxPmkWjSHz6ooPn5XiKSHFgeraLkK8Bkocf24K22wdx5PIxonZSnE13lRcn5Lj7fW7fg6eI3uP9W+MJD3JmEFDyw6KsmwvaWlxykMaRJjfunfBlXVGUZSSlG65peWG06x7pulznjt1+n/P9Ex3/GuPeRLZN/pUHhgJDRRjCTBQCgUNheBHH9iVeOtzJoKFjvm2U8+s4oC8elP6/msuquo9HUP6rIxMP69SidryhlzGmFGtRh92hn3n0Hu1H88AKTOfcWFosmL0+cQaKq6WdDc167r54jZG18PDKH7DG1O/yvtOzneXW+qVbS273R7BCMofdDb3PuSb46usMMTenq4ehXNpipR0=
