sudo: required
dist: trusty
os: linux
language: node_js
node_js:
- '8'
python:
- '3.4'
cache:
  directories:
  - node_modules
before_install:
- echo $authfile | gpg --passphrase-fd 0 src/auth.json.gpg
- sudo apt-get update -y
- sudo apt-get install -y libcairo2-dev libjpeg-dev libpango1.0-dev libgif-dev build-essential
  g++ python3.4
- npm install -g node-pre-gyp node-gyp yarn
- echo "alias python=python3" >> .bashrc
- source .bashrc
before_script:
- yarn add sqlite
install:
- yarn install
script:
- yarn run lint
- yarn test
notifications:
  email: false
env:
  global:
  - secure: "i2+9+O1Q467qthux15C50SNcumSgxMzwEyqbeEnWgBWT593GbH5c7bKO3+jmYe84m5vQpCOzkh+4vNtEVjGAbmcrPje1lQiIobjrUNbuvmdG1J0JWflFhwqlVuktuZa9QRIOxDj58pbyPixSHFCD0hJXgtJHcfELomE8LdH88i/Zlf0cnmn5ZZm6Uy+zk02WJOao+GcLMbDBxmkCajxxI7j3g/nlSPwXmGDSJIa/F3pdisI9MILC540Bvw/QSoNZIRK87jSMMxr8L1odr7cob2voMDmtQk0FuNFCJqki7clQaxVWaQcxhV4cDWGht4anlauX/aAC7lNcO3HjlCNjaZCvIGXH1pZBCRDTP9Nerfpzk53Ie1gUNT+6KQFvLWkTToA/Q4qBKyWp4hUnVNg37DLAQK+CJQE67IWQ5vTA1zVQr3CAnTDd+JQfNa0sCvBTgkLH+EtoEm8f3u0vaYcn6phdd+c5LHhKNoboW4BD55qrlLTRUWftS9YtVdN9cPS/q/YAH4fgSpePBTRo4qWvZZzKaKowxlDlKmVf32dsNi7BuTzp2WnTwjXCxwNm8RElPtG9/TfIBbaQsw/sDgA8vuFwBIiUOEcBLfgizOetgPRXdx4fNBAij9JY7A4uSl/6jSBaU6HJs9T47f9xL/jKZhq0BU10k5AHQy7TUH74OFU="