sudo: required
dist: trusty
os: linux
language: node_js
node_js:
- '8'
python:
- '3.4'
cache:
  directories:
  - node_modules
before_install:
- echo $authfile | gpg --passphrase-fd 0 src/auth.json.gpg
- sudo apt-get update -y
- sudo apt-get install -y libcairo2-dev libjpeg-dev libpango1.0-dev libgif-dev build-essential
  g++ python3.4
- npm install -g node-pre-gyp node-gyp yarn
- echo "alias python=python3" >> .bashrc
- source .bashrc
before_script:
- yarn add sqlite
install:
- yarn install
script:
- yarn run lint
- yarn test
notifications:
  email: false
env:
  global:
    secure: QSfhi7q3OsfPPnoteBk18eM50ysfHFBlwk2s5ASwb6fbW9LPZ2HYKrwACJfnjWym2+LpbM3jG/R9l90k+Ahpgxkym0Ihk3ldgzBSgObkDg++m9hvoEpONAVK+n+G0hfB50BX8GmKqThCgxMncQVTkWWFgsRYN6TYlFvcbQEip/OuOFdDgfThaS37+FlbAVWZYBpCrlRfVDPRV2cHIrupWZvk94pzm607YWS3naC3g7rwQOSsRhMfhSOhSMUN/AcpbWDqisdKrdI6NQsBYF/UFDiuxXL/Q8id3Q1r8Q7SpOpaw7bV7rZXlp2uoqwunyF5pnKNaU/CCWTfXxCuORd4ECKrUakDOw4z7jbMoJsmYhpyB6A6dNo9aRF3L3sw7oaU54gsU+T+s1hKpDorW6w6eOZwWjLlTeRDAhRFdBA0T0G7fNd6/OToNZ1KuRKmkOojopw6YS4XBlhRu43PXS2ToaNO/NyNCjVPG7wPN8Dz8TfLCGuxZl87+X/Z3fC1Jz4/Mde8M6GYHYwOAJBmrXR3Jcc8kFQZRlqI3KZM0oxOVkrtgA+Q3vT6yAltUklefjHCwWYs0YRAhSU13vVNqCL9PpHX+U9wz2jvpMIAMXx5Qaa5Ie0YKQjN4t+OL5JzijjrPMFd9H/TccCiIW1gvQXmgKRYg0nN6BfUz7eyOw3tjPQ=
