version: 2
machine:
  environment:
    PATH: "${PATH}:${HOME}/${Ribbon}/node_modules/.bin"
    NODE_ENV: test
  node:
    version: 8.11.1
  npm:
    version: 5.7.1
dependencies:
  pre:
    - curl -o- -L https://yarnpkg.com/install.sh | bash
  override:
    - yarn
  cache_directories:
    - ~/.cache/yarn
general:
  branches:
    only:
      - master
test:
  override:
    - yarn test
jobs:
  build:
    docker:
      - image: circleci/node:8
    working_directory: ~/ribbon
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run: sudo apt-get update -y && sudo apt-get upgrade -y
      - run: sudo apt-get install -y libcairo2-dev libjpeg-dev libpango1.0-dev libgif-dev build-essential g++ python3.4 yarn
      - run: sudo npm install -g node-pre-gyp node-gyp yarn
      - run: sudo echo "alias python=python3" >> .bashrc
      - run: source .bashrc
      - run: sudo yarn add sqlite
      - run: sudo yarn install
      - run: openssl aes-256-cbc -d -k "$authdecrypt" -in src/auth.json.enc -out src/auth.json
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: yarn test
notify:
  webhooks:
    - url: https://skyhook.glitch.me/api/webhooks/431587377799233537/_kvV2bj5VcFeDX7gf5LmdwQIdVF_bA0xG_zYg-06-LPz8uZbiWLj2oH-1DX_vj1SsrSQ/circleci