version: 2
machine:
  environment:
    PATH: "${PATH}:${HOME}/${CIRCLE_PROJECT_REPONAME}/node_modules/.bin"
dependencies:
  pre:
    - curl -o- -L https://yarnpkg.com/install.sh | bash
  override:
    - yarn
  cache_directories:
    - ~/.cache/yarn
general:
  branches:
    only:
      - master
jobs:
  build:
    docker:
      - image: circleci/node:8
    working_directory: ~/ribbon
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run: sudo apt-get update -y
      - run: sudo apt-get install -y libcairo2-dev libjpeg-dev libpango1.0-dev libgif-dev build-essential g++ python3.4
      - run: sudo npm install -g node-pre-gyp node-gyp yarn
      - run: sudo echo "alias python=python3" >> .bashrc
      - run: source .bashrc
      - run: yarn add sqlite
      - run: yarn install
      - run: openssl aes-256-cbc -d -k "$authdecrypt" -in src/auth.json.enc -out src/auth.json
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: yarn lintfix
      - run: yarn lint
      - run: yarn test
notify:
  webhooks:
    - url: https://skyhook.glitch.me/api/webhooks/309495189901279242/dAOJX74JP1k0dZ9mXdvK923dxLBa3X8jRXcQ49IGI_WgRS_HWId-Qx1_npC-s4vbt4xp/circleci